
export const currenciesList = [
    { code: 'AED', name: 'United Arab Emirates Dirham', symbol: 'AED' },
    { code: 'AFN', name: 'Afghan Afghani', symbol: '؋' },
    { code: 'ALL', name: 'Albanian Lek', symbol: 'L' },
    { code: 'AMD', name: 'Armenian Dram', symbol: '֏' },
    { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ' },
    { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz' },
    { code: 'ARS', name: 'Argentine Peso', symbol: '$' },
    { code: 'AUD', name: 'Australian Dollar', symbol: '$' },
    { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ' },
    { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼' },
    { code: 'BAM', name: 'Bosnia-Herz. Convertible Mark', symbol: 'KM' },
    { code: 'BBD', name: 'Barbadian Dollar', symbol: '$' },
    { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳' },
    { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв' },
    { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب' },
    { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu' },
    { code: 'BMD', name: 'Bermudan Dollar', symbol: '$' },
    { code: 'BND', name: 'Brunei Dollar', symbol: '$' },
    { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.' },
    { code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
    { code: 'BSD', name: 'Bahamian Dollar', symbol: '$' },
    { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.' },
    { code: 'BWP', name: 'Botswanan Pula', symbol: 'P' },
    { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br' },
    { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$' },
    { code: 'CAD', name: 'Canadian Dollar', symbol: '$' },
    { code: 'CDF', name: 'Congolese Franc', symbol: 'FC' },
    { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF' },
    { code: 'CLP', name: 'Chilean Peso', symbol: '$' },
    { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
    { code: 'COP', name: 'Colombian Peso', symbol: '$' },
    { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡' },
    { code: 'CUP', name: 'Cuban Peso', symbol: '₱' },
    { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$' },
    { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč' },
    { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj' },
    { code: 'DKK', name: 'Danish Krone', symbol: 'kr' },
    { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$' },
    { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج' },
    { code: 'EGP', name: 'Egyptian Pound', symbol: '£' },
    { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk' },
    { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br' },
    { code: 'EUR', name: 'Euro', symbol: '€' },
    { code: 'FJD', name: 'Fijian Dollar', symbol: '$' },
    { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£' },
    { code: 'GBP', name: 'British Pound Sterling', symbol: '£' },
    { code: 'GEL', name: 'Georgian Lari', symbol: '₾' },
    { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵' },
    { code: 'GIP', name: 'Gibraltar Pound', symbol: '£' },
    { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D' },
    { code: 'GNF', name: 'Guinean Franc', symbol: 'FG' },
    { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q' },
    { code: 'GYD', name: 'Guyanaese Dollar', symbol: '$' },
    { code: 'HKD', name: 'Hong Kong Dollar', symbol: '$' },
    { code: 'HNL', name: 'Honduran Lempira', symbol: 'L' },
    { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn' },
    { code: 'HTG', name: 'Haitian Gourde', symbol: 'G' },
    { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft' },
    { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp' },
    { code: 'ILS', name: 'Israeli New Sheqel', symbol: '₪' },
    { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
    { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د' },
    { code: 'IRR', name: 'Iranian Rial', symbol: '﷼' },
    { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr' },
    { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$' },
    { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا' },
    { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
    { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh' },
    { code: 'KGS', name: 'Kyrgystani Som', symbol: 'с' },
    { code: 'KHR', name: 'Cambodian Riel', symbol: '៛' },
    { code: 'KMF', name: 'Comorian Franc', symbol: 'CF' },
    { code: 'KPW', name: 'North Korean Won', symbol: '₩' },
    { code: 'KRW', name: 'South Korean Won', symbol: '₩' },
    { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك' },
    { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$' },
    { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸' },
    { code: 'LAK', name: 'Laotian Kip', symbol: '₭' },
    { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل' },
    { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs' },
    { code: 'LRD', name: 'Liberian Dollar', symbol: '$' },
    { code: 'LSL', name: 'Lesotho Loti', symbol: 'L' },
    { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د' },
    { code: 'MAD', name: 'Moroccan Dirham', symbol: 'd.m.' },
    { code: 'MDL', name: 'Moldovan Leu', symbol: 'L' },
    { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar' },
    { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден' },
    { code: 'MMK', name: 'Burmese Kyat', symbol: 'K' },
    { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮' },
    { code: 'MOP', name: 'Macanese Pataca', symbol: 'P' },
    { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM' },
    { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨' },
    { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf' },
    { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK' },
    { code: 'MXN', name: 'Mexican Peso', symbol: '$' },
    { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM' },
    { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT' },
    { code: 'NAD', name: 'Namibian Dollar', symbol: '$' },
    { code: 'NGN', name: 'Nigerian Naira', symbol: '₦' },
    { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$' },
    { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr' },
    { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨' },
    { code: 'NZD', name: 'New Zealand Dollar', symbol: '$' },
    { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.' },
    { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.' },
    { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/.' },
    { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K' },
    { code: 'PHP', name: 'Philippine Peso', symbol: '₱' },
    { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨' },
    { code: 'PLN', name: 'Polish Zloty', symbol: 'zł' },
    { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲' },
    { code: 'QAR', name: 'Qatari Rial', symbol: 'ر.ق' },
    { code: 'RON', name: 'Romanian Leu', symbol: 'lei' },
    { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.' },
    { code: 'RUB', name: 'Russian Ruble', symbol: '₽' },
    { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw' },
    { code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س' },
    { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$' },
    { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨' },
    { code: 'SDG', name: 'Sudanese Pound', symbol: '£' },
    { code: 'SEK', name: 'Swedish Krona', symbol: 'kr' },
    { code: 'SGD', name: 'Singapore Dollar', symbol: '$' },
    { code: 'SHP', name: 'Saint Helena Pound', symbol: '£' },
    { code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le' },
    { code: 'SOS', name: 'Somali Shilling', symbol: 'S' },
    { code: 'SRD', name: 'Surinamese Dollar', symbol: '$' },
    { code: 'SSP', name: 'South Sudanese Pound', symbol: '£' },
    { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db' },
    { code: 'SYP', name: 'Syrian Pound', symbol: '£' },
    { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L' },
    { code: 'THB', name: 'Thai Baht', symbol: '฿' },
    { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅM' },
    { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm' },
    { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت' },
    { code: 'TOP', name: 'Tongan Pa\'anga', symbol: 'T$' },
    { code: 'TRY', name: 'Turkish Lira', symbol: '₺' },
    { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$' },
    { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$' },
    { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh' },
    { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴' },
    { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh' },
    { code: 'USD', name: 'United States Dollar', symbol: '$' },
    { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U' },
    { code: 'UZS', name: 'Uzbekistan Som', symbol: 'so\'m' },
    { code: 'VES', name: 'Venezuelan Bolívar Soberano', symbol: 'Bs.S.' },
    { code: 'VND', name: 'Vietnamese Dong', symbol: '₫' },
    { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT' },
    { code: 'WST', name: 'Samoan Tala', symbol: 'T' },
    { code: 'XAF', name: 'CFA Franc BEAC', symbol: 'FCFA' },
    { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$' },
    { code: 'XOF', name: 'CFA Franc BCEAO', symbol: 'CFA' },
    { code: 'XPF', name: 'CFP Franc', symbol: '₣' },
    { code: 'YER', name: 'Yemeni Rial', symbol: '﷼' },
    { code: 'ZAR', name: 'South African Rand', symbol: 'R' },
    { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK' },
    { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: '$' }
];

export const countriesList = [
    { iso2: 'AF', iso3: 'AFG', name: 'Afghanistan', flag: '🇦🇫', region: 'Asia' },
    { iso2: 'AL', iso3: 'ALB', name: 'Albania', flag: '🇦🇱', region: 'Europe' },
    { iso2: 'DZ', iso3: 'DZA', name: 'Algeria', flag: '🇩🇿', region: 'Africa' },
    { iso2: 'AS', iso3: 'ASM', name: 'American Samoa', flag: '🇦🇸', region: 'Oceania' },
    { iso2: 'AD', iso3: 'AND', name: 'Andorra', flag: '🇦🇩', region: 'Europe' },
    { iso2: 'AO', iso3: 'AGO', name: 'Angola', flag: '🇦🇴', region: 'Africa' },
    { iso2: 'AI', iso3: 'AIA', name: 'Anguilla', flag: '🇦🇮', region: 'Americas' },
    { iso2: 'AQ', iso3: 'ATA', name: 'Antarctica', flag: '🇦🇶', region: 'Polar' },
    { iso2: 'AG', iso3: 'ATG', name: 'Antigua and Barbuda', flag: '🇦🇬', region: 'Americas' },
    { iso2: 'AR', iso3: 'ARG', name: 'Argentina', flag: '🇦🇷', region: 'Americas' },
    { iso2: 'AM', iso3: 'ARM', name: 'Armenia', flag: '🇦🇲', region: 'Asia' },
    { iso2: 'AW', iso3: 'ABW', name: 'Aruba', flag: '🇦🇼', region: 'Americas' },
    { iso2: 'AU', iso3: 'AUS', name: 'Australia', flag: '🇦🇺', region: 'Oceania' },
    { iso2: 'AT', iso3: 'AUT', name: 'Austria', flag: '🇦🇹', region: 'Europe' },
    { iso2: 'AZ', iso3: 'AZE', name: 'Azerbaijan', flag: '🇦🇿', region: 'Asia' },
    { iso2: 'BS', iso3: 'BHS', name: 'Bahamas', flag: '🇧🇸', region: 'Americas' },
    { iso2: 'BH', iso3: 'BHR', name: 'Bahrain', flag: '🇧🇭', region: 'Asia' },
    { iso2: 'BD', iso3: 'BGD', name: 'Bangladesh', flag: '🇧🇩', region: 'Asia' },
    { iso2: 'BB', iso3: 'BRB', name: 'Barbados', flag: '🇧🇧', region: 'Americas' },
    { iso2: 'BY', iso3: 'BLR', name: 'Belarus', flag: '🇧🇾', region: 'Europe' },
    { iso2: 'BE', iso3: 'BEL', name: 'Belgium', flag: '🇧🇪', region: 'Europe' },
    { iso2: 'BZ', iso3: 'BLZ', name: 'Belize', flag: '🇧🇿', region: 'Americas' },
    { iso2: 'BJ', iso3: 'BEN', name: 'Benin', flag: '🇧🇯', region: 'Africa' },
    { iso2: 'BM', iso3: 'BMU', name: 'Bermuda', flag: '🇧🇲', region: 'Americas' },
    { iso2: 'BT', iso3: 'BTN', name: 'Bhutan', flag: '🇧🇹', region: 'Asia' },
    { iso2: 'BO', iso3: 'BOL', name: 'Bolivia', flag: '🇧🇴', region: 'Americas' },
    { iso2: 'BA', iso3: 'BIH', name: 'Bosnia and Herzegovina', flag: '🇧🇦', region: 'Europe' },
    { iso2: 'BW', iso3: 'BWA', name: 'Botswana', flag: '🇧🇼', region: 'Africa' },
    { iso2: 'BR', iso3: 'BRA', name: 'Brazil', flag: '🇧🇷', region: 'Americas' },
    { iso2: 'IO', iso3: 'IOT', name: 'British Indian Ocean Territory', flag: '🇮🇴', region: 'Africa' },
    { iso2: 'BN', iso3: 'BRN', name: 'Brunei Darussalam', flag: '🇧🇳', region: 'Asia' },
    { iso2: 'BG', iso3: 'BGR', name: 'Bulgaria', flag: '🇧🇬', region: 'Europe' },
    { iso2: 'BF', iso3: 'BFA', name: 'Burkina Faso', flag: '🇧🇫', region: 'Africa' },
    { iso2: 'BI', iso3: 'BDI', name: 'Burundi', flag: '🇧🇮', region: 'Africa' },
    { iso2: 'KH', iso3: 'KHM', name: 'Cambodia', flag: '🇰🇭', region: 'Asia' },
    { iso2: 'CM', iso3: 'CMR', name: 'Cameroon', flag: '🇨🇲', region: 'Africa' },
    { iso2: 'CA', iso3: 'CAN', name: 'Canada', flag: '🇨🇦', region: 'Americas' },
    { iso2: 'CV', iso3: 'CPV', name: 'Cape Verde', flag: '🇨🇻', region: 'Africa' },
    { iso2: 'KY', iso3: 'CYM', name: 'Cayman Islands', flag: '🇰🇾', region: 'Americas' },
    { iso2: 'CF', iso3: 'CAF', name: 'Central African Republic', flag: '🇨🇫', region: 'Africa' },
    { iso2: 'TD', iso3: 'TCD', name: 'Chad', flag: '🇹🇩', region: 'Africa' },
    { iso2: 'CL', iso3: 'CHL', name: 'Chile', flag: '🇨🇱', region: 'Americas' },
    { iso2: 'CN', iso3: 'CHN', name: 'China', flag: '🇨🇳', region: 'Asia' },
    { iso2: 'CX', iso3: 'CXR', name: 'Christmas Island', flag: '🇨🇽', region: 'Oceania' },
    { iso2: 'CC', iso3: 'CCK', name: 'Cocos (Keeling) Islands', flag: '🇨🇨', region: 'Oceania' },
    { iso2: 'CO', iso3: 'COL', name: 'Colombia', flag: '🇨🇴', region: 'Americas' },
    { iso2: 'KM', iso3: 'COM', name: 'Comoros', flag: '🇰🇲', region: 'Africa' },
    { iso2: 'CG', iso3: 'COG', name: 'Congo', flag: '🇨🇬', region: 'Africa' },
    { iso2: 'CD', iso3: 'COD', name: 'Congo, Democratic Republic of the', flag: '🇨🇩', region: 'Africa' },
    { iso2: 'CK', iso3: 'COK', name: 'Cook Islands', flag: '🇨🇰', region: 'Oceania' },
    { iso2: 'CR', iso3: 'CRI', name: 'Costa Rica', flag: '🇨🇷', region: 'Americas' },
    { iso2: 'CI', iso3: 'CIV', name: 'Cote D\'Ivoire', flag: '🇨🇮', region: 'Africa' },
    { iso2: 'HR', iso3: 'HRV', name: 'Croatia', flag: '🇭🇷', region: 'Europe' },
    { iso2: 'CU', iso3: 'CUB', name: 'Cuba', flag: '🇨🇺', region: 'Americas' },
    { iso2: 'CY', iso3: 'CYP', name: 'Cyprus', flag: '🇨🇾', region: 'Asia' },
    { iso2: 'CZ', iso3: 'CZE', name: 'Czech Republic', flag: '🇨🇿', region: 'Europe' },
    { iso2: 'DK', iso3: 'DNK', name: 'Denmark', flag: '🇩🇰', region: 'Europe' },
    { iso2: 'DJ', iso3: 'DJI', name: 'Djibouti', flag: '🇩🇯', region: 'Africa' },
    { iso2: 'DM', iso3: 'DMA', name: 'Dominica', flag: '🇩🇲', region: 'Americas' },
    { iso2: 'DO', iso3: 'DOM', name: 'Dominican Republic', flag: '🇩🇴', region: 'Americas' },
    { iso2: 'EC', iso3: 'ECU', name: 'Ecuador', flag: '🇪🇨', region: 'Americas' },
    { iso2: 'EG', iso3: 'EGY', name: 'Egypt', flag: '🇪🇬', region: 'Africa' },
    { iso2: 'SV', iso3: 'SLV', name: 'El Salvador', flag: '🇸🇻', region: 'Americas' },
    { iso2: 'GQ', iso3: 'GNQ', name: 'Equatorial Guinea', flag: '🇬🇶', region: 'Africa' },
    { iso2: 'ER', iso3: 'ERI', name: 'Eritrea', flag: '🇪🇷', region: 'Africa' },
    { iso2: 'EE', iso3: 'EST', name: 'Estonia', flag: '🇪🇪', region: 'Europe' },
    { iso2: 'ET', iso3: 'ETH', name: 'Ethiopia', flag: '🇪🇹', region: 'Africa' },
    { iso2: 'FK', iso3: 'FLK', name: 'Falkland Islands (Malvinas)', flag: '🇫🇰', region: 'Americas' },
    { iso2: 'FO', iso3: 'FRO', name: 'Faroe Islands', flag: '🇫🇴', region: 'Europe' },
    { iso2: 'FJ', iso3: 'FJI', name: 'Fiji', flag: '🇫🇯', region: 'Oceania' },
    { iso2: 'FI', iso3: 'FIN', name: 'Finland', flag: '🇫🇮', region: 'Europe' },
    { iso2: 'FR', iso3: 'FRA', name: 'France', flag: '🇫🇷', region: 'Europe' },
    { iso2: 'GF', iso3: 'GUF', name: 'French Guiana', flag: '🇬🇫', region: 'Americas' },
    { iso2: 'PF', iso3: 'PYF', name: 'French Polynesia', flag: '🇵🇫', region: 'Oceania' },
    { iso2: 'GA', iso3: 'GAB', name: 'Gabon', flag: '🇬🇦', region: 'Africa' },
    { iso2: 'GM', iso3: 'GMB', name: 'Gambia', flag: '🇬🇲', region: 'Africa' },
    { iso2: 'GE', iso3: 'GEO', name: 'Georgia', flag: '🇬🇪', region: 'Asia' },
    { iso2: 'DE', iso3: 'DEU', name: 'Germany', flag: '🇩🇪', region: 'Europe' },
    { iso2: 'GH', iso3: 'GHA', name: 'Ghana', flag: '🇬🇭', region: 'Africa' },
    { iso2: 'GI', iso3: 'GIB', name: 'Gibraltar', flag: '🇬🇮', region: 'Europe' },
    { iso2: 'GR', iso3: 'GRC', name: 'Greece', flag: '🇬🇷', region: 'Europe' },
    { iso2: 'GL', iso3: 'GRL', name: 'Greenland', flag: '🇬🇱', region: 'Americas' },
    { iso2: 'GD', iso3: 'GRD', name: 'Grenada', flag: '🇬🇩', region: 'Americas' },
    { iso2: 'GP', iso3: 'GLP', name: 'Guadeloupe', flag: '🇬🇵', region: 'Americas' },
    { iso2: 'GU', iso3: 'GUM', name: 'Guam', flag: '🇬🇺', region: 'Oceania' },
    { iso2: 'GT', iso3: 'GTM', name: 'Guatemala', flag: '🇬🇹', region: 'Americas' },
    { iso2: 'GN', iso3: 'GIN', name: 'Guinea', flag: '🇬🇳', region: 'Africa' },
    { iso2: 'GW', iso3: 'GNB', name: 'Guinea-Bissau', flag: '🇬🇼', region: 'Africa' },
    { iso2: 'GY', iso3: 'GUY', name: 'Guyana', flag: '🇬🇾', region: 'Americas' },
    { iso2: 'HT', iso3: 'HTI', name: 'Haiti', flag: '🇭🇹', region: 'Americas' },
    { iso2: 'HN', iso3: 'HND', name: 'Honduras', flag: '🇭🇳', region: 'Americas' },
    { iso2: 'HK', iso3: 'HKG', name: 'Hong Kong', flag: '🇭🇰', region: 'Asia' },
    { iso2: 'HU', iso3: 'HUN', name: 'Hungary', flag: '🇭🇺', region: 'Europe' },
    { iso2: 'IS', iso3: 'ISL', name: 'Iceland', flag: '🇮🇸', region: 'Europe' },
    { iso2: 'IN', iso3: 'IND', name: 'India', flag: '🇮🇳', region: 'Asia' },
    { iso2: 'ID', iso3: 'IDN', name: 'Indonesia', flag: '🇮🇩', region: 'Asia' },
    { iso2: 'IR', iso3: 'IRN', name: 'Iran, Islamic Republic of', flag: '🇮🇷', region: 'Asia' },
    { iso2: 'IQ', iso3: 'IRQ', name: 'Iraq', flag: '🇮🇶', region: 'Asia' },
    { iso2: 'IE', iso3: 'IRL', name: 'Ireland', flag: '🇮🇪', region: 'Europe' },
    { iso2: 'IL', iso3: 'ISR', name: 'Israel', flag: '🇮🇱', region: 'Asia' },
    { iso2: 'IT', iso3: 'ITA', name: 'Italy', flag: '🇮🇹', region: 'Europe' },
    { iso2: 'JM', iso3: 'JAM', name: 'Jamaica', flag: '🇯🇲', region: 'Americas' },
    { iso2: 'JP', iso3: 'JPN', name: 'Japan', flag: '🇯🇵', region: 'Asia' },
    { iso2: 'JO', iso3: 'JOR', name: 'Jordan', flag: '🇯🇴', region: 'Asia' },
    { iso2: 'KZ', iso3: 'KAZ', name: 'Kazakhstan', flag: '🇰🇿', region: 'Asia' },
    { iso2: 'KE', iso3: 'KEN', name: 'Kenya', flag: '🇰🇪', region: 'Africa' },
    { iso2: 'KI', iso3: 'KIR', name: 'Kiribati', flag: '🇰🇮', region: 'Oceania' },
    { iso2: 'KP', iso3: 'PRK', name: 'Korea, Democratic People\'s Republic of', flag: '🇰🇵', region: 'Asia' },
    { iso2: 'KR', iso3: 'KOR', name: 'Korea, Republic of', flag: '🇰🇷', region: 'Asia' },
    { iso2: 'KW', iso3: 'KWT', name: 'Kuwait', flag: '🇰🇼', region: 'Asia' },
    { iso2: 'KG', iso3: 'KGZ', name: 'Kyrgyzstan', flag: '🇰🇬', region: 'Asia' },
    { iso2: 'LA', iso3: 'LAO', name: 'Lao People\'s Democratic Republic', flag: '🇱🇦', region: 'Asia' },
    { iso2: 'LV', iso3: 'LVA', name: 'Latvia', flag: '🇱🇻', region: 'Europe' },
    { iso2: 'LB', iso3: 'LBN', name: 'Lebanon', flag: '🇱🇧', region: 'Asia' },
    { iso2: 'LS', iso3: 'LSO', name: 'Lesotho', flag: '🇱🇸', region: 'Africa' },
    { iso2: 'LR', iso3: 'LBR', name: 'Liberia', flag: '🇱🇷', region: 'Africa' },
    { iso2: 'LY', iso3: 'LBY', name: 'Libyan Arab Jamahiriya', flag: '🇱🇾', region: 'Africa' },
    { iso2: 'LI', iso3: 'LIE', name: 'Liechtenstein', flag: '🇱🇮', region: 'Europe' },
    { iso2: 'LT', iso3: 'LTU', name: 'Lithuania', flag: '🇱🇹', region: 'Europe' },
    { iso2: 'LU', iso3: 'LUX', name: 'Luxembourg', flag: '🇱🇺', region: 'Europe' },
    { iso2: 'MO', iso3: 'MAC', name: 'Macao', flag: '🇲🇴', region: 'Asia' },
    { iso2: 'MK', iso3: 'MKD', name: 'Macedonia, the Former Yugoslav Republic of', flag: '🇲🇰', region: 'Europe' },
    { iso2: 'MG', iso3: 'MDG', name: 'Madagascar', flag: '🇲🇬', region: 'Africa' },
    { iso2: 'MW', iso3: 'MWI', name: 'Malawi', flag: '🇲🇼', region: 'Africa' },
    { iso2: 'MY', iso3: 'MYS', name: 'Malaysia', flag: '🇲🇾', region: 'Asia' },
    { iso2: 'MV', iso3: 'MDV', name: 'Maldives', flag: '🇲🇻', region: 'Asia' },
    { iso2: 'ML', iso3: 'MLI', name: 'Mali', flag: '🇲🇱', region: 'Africa' },
    { iso2: 'MT', iso3: 'MLT', name: 'Malta', flag: '🇲🇹', region: 'Europe' },
    { iso2: 'MH', iso3: 'MHL', name: 'Marshall Islands', flag: '🇲🇭', region: 'Oceania' },
    { iso2: 'MQ', iso3: 'MTQ', name: 'Martinique', flag: '🇲🇶', region: 'Americas' },
    { iso2: 'MR', iso3: 'MRT', name: 'Mauritania', flag: '🇲🇷', region: 'Africa' },
    { iso2: 'MU', iso3: 'MUS', name: 'Mauritius', flag: '🇲🇺', region: 'Africa' },
    { iso2: 'YT', iso3: 'MYT', name: 'Mayotte', flag: '🇾🇹', region: 'Africa' },
    { iso2: 'MX', iso3: 'MEX', name: 'Mexico', flag: '🇲🇽', region: 'Americas' },
    { iso2: 'FM', iso3: 'FSM', name: 'Micronesia, Federated States of', flag: '🇫🇲', region: 'Oceania' },
    { iso2: 'MD', iso3: 'MDA', name: 'Moldova, Republic of', flag: '🇲🇩', region: 'Europe' },
    { iso2: 'MC', iso3: 'MCO', name: 'Monaco', flag: '🇲🇨', region: 'Europe' },
    { iso2: 'MN', iso3: 'MNG', name: 'Mongolia', flag: '🇲🇳', region: 'Asia' },
    { iso2: 'MS', iso3: 'MSR', name: 'Montserrat', flag: '🇲🇸', region: 'Americas' },
    { iso2: 'MA', iso3: 'MAR', name: 'Morocco', flag: '🇲🇦', region: 'Africa' },
    { iso2: 'MZ', iso3: 'MOZ', name: 'Mozambique', flag: '🇲🇿', region: 'Africa' },
    { iso2: 'MM', iso3: 'MMR', name: 'Myanmar', flag: '🇲🇲', region: 'Asia' },
    { iso2: 'NA', iso3: 'NAM', name: 'Namibia', flag: '🇳🇦', region: 'Africa' },
    { iso2: 'NR', iso3: 'NRU', name: 'Nauru', flag: '🇳🇷', region: 'Oceania' },
    { iso2: 'NP', iso3: 'NPL', name: 'Nepal', flag: '🇳🇵', region: 'Asia' },
    { iso2: 'NL', iso3: 'NLD', name: 'Netherlands', flag: '🇳🇱', region: 'Europe' },
    { iso2: 'AN', iso3: 'ANT', name: 'Netherlands Antilles', flag: '🇳🇱', region: 'Americas' },
    { iso2: 'NC', iso3: 'NCL', name: 'New Caledonia', flag: '🇳🇨', region: 'Oceania' },
    { iso2: 'NZ', iso3: 'NZL', name: 'New Zealand', flag: '🇳🇿', region: 'Oceania' },
    { iso2: 'NI', iso3: 'NIC', name: 'Nicaragua', flag: '🇳🇮', region: 'Americas' },
    { iso2: 'NE', iso3: 'NER', name: 'Niger', flag: '🇳🇪', region: 'Africa' },
    { iso2: 'NG', iso3: 'NGA', name: 'Nigeria', flag: '🇳🇬', region: 'Africa' },
    { iso2: 'NU', iso3: 'NIU', name: 'Niue', flag: '🇳🇺', region: 'Oceania' },
    { iso2: 'NF', iso3: 'NFK', name: 'Norfolk Island', flag: '🇳🇫', region: 'Oceania' },
    { iso2: 'MP', iso3: 'MNP', name: 'Northern Mariana Islands', flag: '🇲🇵', region: 'Oceania' },
    { iso2: 'NO', iso3: 'NOR', name: 'Norway', flag: '🇳🇴', region: 'Europe' },
    { iso2: 'OM', iso3: 'OMN', name: 'Oman', flag: '🇴🇲', region: 'Asia' },
    { iso2: 'PK', iso3: 'PAK', name: 'Pakistan', flag: '🇵🇰', region: 'Asia' },
    { iso2: 'PW', iso3: 'PLW', name: 'Palau', flag: '🇵🇼', region: 'Oceania' },
    { iso2: 'PS', iso3: 'PSE', name: 'Palestinian Territory, Occupied', flag: '🇵🇸', region: 'Asia' },
    { iso2: 'PA', iso3: 'PAN', name: 'Panama', flag: '🇵🇦', region: 'Americas' },
    { iso2: 'PG', iso3: 'PNG', name: 'Papua New Guinea', flag: '🇵🇬', region: 'Oceania' },
    { iso2: 'PY', iso3: 'PRY', name: 'Paraguay', flag: '🇵🇾', region: 'Americas' },
    { iso2: 'PE', iso3: 'PER', name: 'Peru', flag: '🇵🇪', region: 'Americas' },
    { iso2: 'PH', iso3: 'PHL', name: 'Philippines', flag: '🇵🇭', region: 'Asia' },
    { iso2: 'PN', iso3: 'PCN', name: 'Pitcairn', flag: '🇵🇳', region: 'Oceania' },
    { iso2: 'PL', iso3: 'POL', name: 'Poland', flag: '🇵🇱', region: 'Europe' },
    { iso2: 'PT', iso3: 'PRT', name: 'Portugal', flag: '🇵🇹', region: 'Europe' },
    { iso2: 'PR', iso3: 'PRI', name: 'Puerto Rico', flag: '🇵🇷', region: 'Americas' },
    { iso2: 'QA', iso3: 'QAT', name: 'Qatar', flag: '🇶🇦', region: 'Asia' },
    { iso2: 'RE', iso3: 'REU', name: 'Reunion', flag: '🇷🇪', region: 'Africa' },
    { iso2: 'RO', iso3: 'ROM', name: 'Romania', flag: '🇷🇴', region: 'Europe' },
    { iso2: 'RU', iso3: 'RUS', name: 'Russian Federation', flag: '🇷🇺', region: 'Europe' },
    { iso2: 'RW', iso3: 'RWA', name: 'Rwanda', flag: '🇷🇼', region: 'Africa' },
    { iso2: 'SH', iso3: 'SHN', name: 'Saint Helena', flag: '🇸🇭', region: 'Africa' },
    { iso2: 'KN', iso3: 'KNA', name: 'Saint Kitts and Nevis', flag: '🇰🇳', region: 'Americas' },
    { iso2: 'LC', iso3: 'LCA', name: 'Saint Lucia', flag: '🇱🇨', region: 'Americas' },
    { iso2: 'PM', iso3: 'SPM', name: 'Saint Pierre and Miquelon', flag: '🇵🇲', region: 'Americas' },
    { iso2: 'VC', iso3: 'VCT', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', region: 'Americas' },
    { iso2: 'WS', iso3: 'WSM', name: 'Samoa', flag: '🇼🇸', region: 'Oceania' },
    { iso2: 'SM', iso3: 'SMR', name: 'San Marino', flag: '🇸🇲', region: 'Europe' },
    { iso2: 'ST', iso3: 'STP', name: 'Sao Tome and Principe', flag: '🇸🇹', region: 'Africa' },
    { iso2: 'SA', iso3: 'SAU', name: 'Saudi Arabia', flag: '🇸🇦', region: 'Asia' },
    { iso2: 'SN', iso3: 'SEN', name: 'Senegal', flag: '🇸🇳', region: 'Africa' },
    { iso2: 'CS', iso3: 'SCG', name: 'Serbia and Montenegro', flag: '🇷🇸', region: 'Europe' },
    { iso2: 'SC', iso3: 'SYC', name: 'Seychelles', flag: '🇸🇨', region: 'Africa' },
    { iso2: 'SL', iso3: 'SLE', name: 'Sierra Leone', flag: '🇸🇱', region: 'Africa' },
    { iso2: 'SG', iso3: 'SGP', name: 'Singapore', flag: '🇸🇬', region: 'Asia' },
    { iso2: 'SK', iso3: 'SVK', name: 'Slovakia', flag: '🇸🇰', region: 'Europe' },
    { iso2: 'SI', iso3: 'SVN', name: 'Slovenia', flag: '🇸🇮', region: 'Europe' },
    { iso2: 'SB', iso3: 'SLB', name: 'Solomon Islands', flag: '🇸🇧', region: 'Oceania' },
    { iso2: 'SO', iso3: 'SOM', name: 'Somalia', flag: '🇸🇴', region: 'Africa' },
    { iso2: 'ZA', iso3: 'ZAF', name: 'South Africa', flag: '🇿🇦', region: 'Africa' },
    { iso2: 'GS', iso3: 'SGS', name: 'South Georgia and the South Sandwich Islands', flag: '🇬🇸', region: 'Americas' },
    { iso2: 'ES', iso3: 'ESP', name: 'Spain', flag: '🇪🇸', region: 'Europe' },
    { iso2: 'LK', iso3: 'LKA', name: 'Sri Lanka', flag: '🇱🇰', region: 'Asia' },
    { iso2: 'SD', iso3: 'SDN', name: 'Sudan', flag: '🇸🇩', region: 'Africa' },
    { iso2: 'SR', iso3: 'SUR', name: 'Suriname', flag: '🇸🇷', region: 'Americas' },
    { iso2: 'SJ', iso3: 'SJM', name: 'Svalbard and Jan Mayen', flag: '🇸🇯', region: 'Europe' },
    { iso2: 'SZ', iso3: 'SWZ', name: 'Swaziland', flag: '🇸🇿', region: 'Africa' },
    { iso2: 'SE', iso3: 'SWE', name: 'Sweden', flag: '🇸🇪', region: 'Europe' },
    { iso2: 'CH', iso3: 'CHE', name: 'Switzerland', flag: '🇨🇭', region: 'Europe' },
    { iso2: 'SY', iso3: 'SYR', name: 'Syrian Arab Republic', flag: '🇸🇾', region: 'Asia' },
    { iso2: 'TW', iso3: 'TWN', name: 'Taiwan, Province of China', flag: '🇹🇼', region: 'Asia' },
    { iso2: 'TJ', iso3: 'TJK', name: 'Tajikistan', flag: '🇹🇯', region: 'Asia' },
    { iso2: 'TZ', iso3: 'TZA', name: 'Tanzania, United Republic of', flag: '🇹🇿', region: 'Africa' },
    { iso2: 'TH', iso3: 'THA', name: 'Thailand', flag: '🇹🇭', region: 'Asia' },
    { iso2: 'TL', iso3: 'TLS', name: 'Timor-Leste', flag: '🇹🇱', region: 'Asia' },
    { iso2: 'TG', iso3: 'TGO', name: 'Togo', flag: '🇹🇬', region: 'Africa' },
    { iso2: 'TK', iso3: 'TKL', name: 'Tokelau', flag: '🇹🇰', region: 'Oceania' },
    { iso2: 'TO', iso3: 'TON', name: 'Tonga', flag: '🇹🇴', region: 'Oceania' },
    { iso2: 'TT', iso3: 'TTO', name: 'Trinidad and Tobago', flag: '🇹🇹', region: 'Americas' },
    { iso2: 'TN', iso3: 'TUN', name: 'Tunisia', flag: '🇹🇳', region: 'Africa' },
    { iso2: 'TR', iso3: 'TUR', name: 'Turkey', flag: '🇹🇷', region: 'Asia' },
    { iso2: 'TM', iso3: 'TKM', name: 'Turkmenistan', flag: '🇹🇲', region: 'Asia' },
    { iso2: 'TC', iso3: 'TCA', name: 'Turks and Caicos Islands', flag: '🇹🇨', region: 'Americas' },
    { iso2: 'TV', iso3: 'TUV', name: 'Tuvalu', flag: '🇹🇻', region: 'Oceania' },
    { iso2: 'UG', iso3: 'UGA', name: 'Uganda', flag: '🇺🇬', region: 'Africa' },
    { iso2: 'UA', iso3: 'UKR', name: 'Ukraine', flag: '🇺🇦', region: 'Europe' },
    { iso2: 'UM', iso3: 'UMI', name: 'United States Minor Outlying Islands', flag: '🇺🇸', region: 'Oceania' },
    { iso2: 'UY', iso3: 'URY', name: 'Uruguay', flag: '🇺🇾', region: 'Americas' },
    { iso2: 'UZ', iso3: 'UZB', name: 'Uzbekistan', flag: '🇺🇿', region: 'Asia' },
    { iso2: 'VU', iso3: 'VUT', name: 'Vanuatu', flag: '🇻🇺', region: 'Oceania' },
    { iso2: 'VE', iso3: 'VEN', name: 'Venezuela', flag: '🇻🇪', region: 'Americas' },
    { iso2: 'VN', iso3: 'VNM', name: 'Viet Nam', flag: '🇻🇳', region: 'Asia' },
    { iso2: 'VG', iso3: 'VGB', name: 'Virgin Islands, British', flag: '🇻🇬', region: 'Americas' },
    { iso2: 'VI', iso3: 'VIR', name: 'Virgin Islands, U.S.', flag: '🇻-🇮', region: 'Americas' },
    { iso2: 'WF', iso3: 'WLF', name: 'Wallis and Futuna', flag: '🇼🇫', region: 'Oceania' },
    { iso2: 'EH', iso3: 'ESH', name: 'Western Sahara', flag: '🇪🇭', region: 'Africa' },
    { iso2: 'YE', iso3: 'YEM', name: 'Yemen', flag: '🇾🇪', region: 'Asia' },
    { iso2: 'ZM', iso3: 'ZMB', name: 'Zambia', flag: '🇿🇲', region: 'Africa' },
    { iso2: 'ZW', iso3: 'ZWE', name: 'Zimbabwe', flag: '🇿🇼', region: 'Africa' },
    { iso2: 'US', iso3: 'USA', name: 'United States', flag: '🇺🇸', region: 'Americas' },
    { iso2: 'GB', iso3: 'GBR', name: 'United Kingdom', flag: '🇬🇧', region: 'Europe' },
    { iso2: 'AE', iso3: 'ARE', name: 'United Arab Emirates', flag: '🇦🇪', region: 'Asia' }
];

export const modulesList = [
    { key: 'hms', name: 'Hospital', desc: 'Complete Hospital & Clinical Operations' },
    { key: 'system', name: 'System', desc: 'System Configuration & Admin' },
    { key: 'crm', name: 'CRM', desc: 'Customer Relationship & Pipeline Management' },
    { key: 'finance', name: 'Gateway of Tally', desc: 'General Ledger, Billing, & Financial Reports' },
    { key: 'inventory', name: 'Inventory & SCM', desc: 'Supply Chain, Stock, & Procurement' },
    { key: 'hr', name: 'HR & Payroll', desc: 'Human Capital Management & Payroll Processing' },
    { key: 'analytics', name: 'Analytics & BI', desc: 'Business Intelligence & Data Visualization' },
    { key: 'projects', name: 'Project Management', desc: 'Task Tracking, Milestones & Collaboration' },
    { key: 'assets', name: 'Asset Management', desc: 'Fixed Asset Tracking & Maintenance' },
    { key: 'pos', name: 'Point of Sale (POS)', desc: 'Retail & Pharmacy Billing Terminals' },
    { key: 'documents', name: 'Document Management', desc: 'Secure File Storage & Digital Archiving' },
    { key: 'communication', name: 'Communication', desc: 'Internal Chat, Email & Notifications' },
    { key: 'learning', name: 'LMS', desc: 'Learning Management & Employee Training' }
];
